name: Test dns-lookup crate

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable, nightly]

    steps:
    - uses: hecrj/setup-rust-action@v1
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@master
    - name: Run tests
      run: cargo test --verbose

    timeout-minutes: 10

  haiku:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: cpa.sh {0}

    steps:
    - uses: actions/checkout@master
    - name: Start Haiku VM
      uses: cross-platform-actions/action@v1.5.0
      with:
        operating_system: haiku
        architecture: x86-64
        version: 'r1beta6'
        shell: bash
        environment_variables: CARGO_TERM_COLOR
    - name: Install Rust
      run: pkgman install -y rust_bin
    - name: Run tests
      run: cargo test --verbose

    timeout-minutes: 30

  msrv:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - name: Install tools
      uses: taiki-e/install-action@v2
      with:
        tool: |
          cargo-hack
          cargo-minimal-versions
      
    - uses: actions/checkout@master
    - name: Run tests
      run: cargo minimal-versions test --rust-version --verbose

    timeout-minutes: 10
